"""empty message

Revision ID: 0af34e8ea563
Revises: 0f2018bd6dd6
Create Date: 2024-04-17 13:39:16.220887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af34e8ea563'
down_revision: Union[str, None] = '0f2018bd6dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('weather_id', sa.Integer(), nullable=False))
    op.drop_column('weather_data', 'record_id')
    op.add_column('wind_data', sa.Column('wind_id', sa.Integer(), nullable=False))
    op.drop_column('wind_data', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind_data', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('wind_data', 'wind_id')
    op.add_column('weather_data', sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('weather_data', 'weather_id')
    # ### end Alembic commands ###
