"""empty message

Revision ID: 3bf835066425
Revises: de1cf1188ee0
Create Date: 2024-04-17 12:35:20.132519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf835066425'
down_revision: Union[str, None] = 'de1cf1188ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_data', 'country_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
