"""8

Revision ID: 56733b61aec9
Revises: 91f45a65b526
Create Date: 2024-04-19 11:55:05.851983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56733b61aec9'
down_revision: Union[str, None] = '91f45a65b526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('weather_id_unique_constraint', 'weather_data', ['weather_id'])
    op.add_column('wind_data', sa.Column('weather_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wind_data', 'weather_data', ['weather_id'], ['weather_id'])
    op.drop_column('wind_data', 'last_updated_epoch')
    op.drop_column('wind_data', 'last_updated')
    op.drop_column('wind_data', 'wind_id')
    op.drop_column('wind_data', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind_data', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('wind_data', sa.Column('wind_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('wind_data', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('wind_data', sa.Column('last_updated_epoch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wind_data', type_='foreignkey')
    op.drop_column('wind_data', 'weather_id')
    op.drop_constraint('weather_id_unique_constraint', 'weather_data', type_='unique')
    # ### end Alembic commands ###
