"""empty message

Revision ID: de1cf1188ee0
Revises: 
Create Date: 2024-04-17 12:11:04.626033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'de1cf1188ee0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.Column('country', sa.String(length=255), nullable=True),
                    sa.Column('location_name', sa.String(length=255), nullable=True),
                    sa.Column('latitude', sa.Numeric(precision=10, scale=2), nullable=True),
                    sa.Column('longitude', sa.Numeric(precision=10, scale=2), nullable=True),
                    sa.Column('timezone', sa.String(length=255), nullable=True),
                    sa.Column('last_updated_epoch', sa.Integer(), nullable=True),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.Column('temperature_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('temperature_fahrenheit', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('condition_text', sa.String(length=255), nullable=True),
                    sa.Column('wind_mph', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('wind_kph', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('wind_degree', sa.Integer(), nullable=True),
                    sa.Column('wind_direction', sa.String(length=3), nullable=True),
                    sa.Column('pressure_mb', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('pressure_in', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('precip_mm', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('precip_in', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('humidity', sa.Integer(), nullable=True),
                    sa.Column('cloud', sa.Integer(), nullable=True),
                    sa.Column('feels_like_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('feels_like_fahrenheit', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('visibility_km', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('visibility_miles', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('uv_index', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('gust_mph', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('gust_kph', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.Column('air_quality_Carbon_Monoxide', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('air_quality_Ozone', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('air_quality_Nitrogen_dioxide', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('air_quality_Sulphur_dioxide', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('air_quality_PM25', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('air_quality_PM10', sa.Numeric(precision=6, scale=2), nullable=True),
                    sa.Column('air_quality_us_epa_index', sa.Integer(), nullable=True),
                    sa.Column('air_quality_gb_defra_index', sa.Integer(), nullable=True),
                    sa.Column('sunrise', sa.Time(), nullable=True),
                    sa.Column('sunset', sa.Time(), nullable=True),
                    sa.Column('moonrise', sa.Time(), nullable=True),
                    sa.Column('moonset', sa.Time(), nullable=True),
                    sa.Column('moon_phase', sa.String(length=255), nullable=True),
                    sa.Column('moon_illumination', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    # ### end Alembic commands ###
